### ISSUE TITLE
Does not render vue from renderer!

### ISSUE THREAD

**Issue by emgould** [chrisvfritz/vue-ssr-demo-simple#3]
This example does nothing more than render the app.js that is hard coded in the index.html.  It does not dynamically render what is rendered from renderFromString.  

if you view source of the rendered page you will see that there is no "server-rendered = true".  A matter of fact,  you could put any valid Vue  in the renderToString as the vue parameter and this will render some the same hardcoded app.

**Comment by chrisvfritz** [comment]
Did you launch the server with `npm run dev` or `npm run prod`? I just confirmed SSR does appear to be working.

**Comment by emgould** [comment]
npm run dev.

**Comment by emgould** [comment]
vue.js is 2.1.8
express 4.1.4

and npm run dev or prod produces same result.  Running on mac os x 10.11.6

**Comment by emgould** [comment]
Ok so, view page source, will show the code that is immediately returned from the server.  However, if you inspect the dom  you will see that the actually rendered ( post javascript ) is actually just the app coming from the app.js.  

This means that there is no "server-side" rendering occurring.  It is effectively just serving the app.js file.  The rendering step is redundant.  You render it and then it will be replaced immediately by the Vue from app.js.    

Maybe I am missing something but this is still client side rendering.

**Comment by chrisvfritz** [comment]
It sounds like you misunderstand what server-side rendering is, because what you're describing is correct behavior. It doesn't mean there's no client-side JavaScript - just that the _initial_ render is server-side. See [the SSR guide](https://vuejs.org/v2/guide/ssr.html#Do-You-Need-SSR) for the benefits.

**Comment by emgould** [comment]
If your vue is not simply a simplistic static page with no dynamic elements then this is not SSR.  It is on-demand pre-rendering.  It will only help with SEO and the other stated benefits if your rendered html is non-dynamic.  Most SPA views are dynamic and leverage async data and event handling.  So SSR benefits as stated will not be realized.  It certainly doesn't help deal with non-javascript, slow-browsers, etc..  

To me,  the meaning of SSR is that all of the functionality of VueJS is delivered but is delivered with the server rendering and updating the client.  Not just some initial render that is immediately swapped out for the client rendered.

**Comment by chrisvfritz** [comment]
It's still better to serve non-JS browsers real content than a blank page. As for slow browsers, perceived page load is still greatly improved. The definitions of SSR and prerendering you're using are simply not the ones used by the rest of the world.

**Comment by emgould** [comment]
Understood.  Thanks.

**Comment by emgould** [comment]
FWIW...I ended up extending express-vue with async data that links the server side with the vue utilizing SockJS.  Thus allowing the vue to render both the initial synchronous server side rendering  and any additional two way asynchronous data binding.  So it may not be the accepted definition but now I am much closer to my definition of server side rendering.
