### ISSUE TITLE
how to render the content of vue-router with vue-ssr?

### ISSUE THREAD

**Issue by dione2017** [chrisvfritz/vue-ssr-demo-simple#4]
in the project, I use router-view ,but finally I got   `<div id="app" server-rendered="true"><div>hello world</div> <router-view></router-view></div>` in the callback of renderer.renderToString

**Comment by chrisvfritz** [comment]
This is a usage question that's outside the scope of this project, so is best suited to either [the forum](http://forum.vuejs.org/) or [the Gitter chat](https://gitter.im/vuejs/vue).
